version: '3'
services:
  postgres:
    image: postgres:12.7
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - "5433:5432"
    command: ["postgres", "-c", "log_statement=all"]